// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqrlskpoakohbgynqeqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxcmxza3BvYWtvaGJneW5xZXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzk2MzgsImV4cCI6MjA2OTk1NTYzOH0.wIlg5RR0q1Dr4UhzSTbge9N7ax-Hwa_FKMbiiV1isUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});